use std::cmp::min;

use crate::*;
use BindingMode::*;
use Mutability::*;

/// The various typing rules we can apply.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Rule {
    Constructor,
    ConstructorRef(DowngradeMutToRef),
    ConstructorMultiRef(DowngradeMutToRef),
    Deref(
        InheritedRefOnRefBehavior,
        DowngradeMutToRef,
        FallbackToOuter,
    ),
    DerefMutWithShared(InheritedRefOnRefBehavior),
    RefBindingResetBindingMode,
    MutBindingResetBindingMode,
    BindingBorrow,
    Binding,
    ExprSimplification,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum DowngradeMutToRef {
    Normal,
    ForceReadOnly,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct FallbackToOuter(pub bool);

#[derive(Debug, Clone, Copy)]
pub enum TypeError {
    TypeMismatch,
    MutabilityMismatch,
    InheritedRefIsAlone,
    RefOnRef,
    MutOnRef,
    OverlyGeneral(DeepeningRequest),
    /// An error generated by running the `ergonomics-formality` solver.
    External(match_ergonomics_formality::StepError),
}

impl<'a> TypingPredicate<'a> {
    /// Apply one step of rule to this predicate.
    /// Note: The `downgrade_mut_inside_shared` option is special: it inspects `self.expr` in
    /// non-trivial ways.
    /// All the other rules inspect `self.pat`, `self.expr.ty`, `self.expr.binding_mode()` up to a
    /// fixed depth. We trigger `OverlyGeneral` errors it the rules needs more information to
    /// decide what to do. This is how we can auto-generate the rules listings.
    pub fn step(&self, ctx: TypingCtx<'a>) -> Result<(Rule, Vec<Self>), TypeError> {
        use DeepeningRequest as D;
        use Pattern as P;
        use Type as T;
        let a = ctx.arenas;
        let o = ctx.options;
        if o.always_inspect_bm && !matches!(self.expr.ty, Type::Abstract(..)) {
            let _ = self.expr.binding_mode()?;
        }

        match (*self.pat, *self.expr.ty) {
            // Constructor rules
            (P::Tuple(pats), T::Tuple(tys)) if pats.len() == tys.len() => {
                let preds = pats
                    .iter()
                    .enumerate()
                    .map(|(i, pat)| {
                        let expr = self.expr.field(a, i);
                        Self { pat, expr }
                    })
                    .collect();
                Ok((Rule::Constructor, preds))
            }
            (P::Tuple(_), T::Tuple(_)) => Err(TypeError::TypeMismatch),
            (P::Tuple(pats), T::Ref(mut mtbl, T::Tuple(tys)))
                if pats.len() == tys.len() && o.match_constructor_through_ref =>
            {
                let mut downgrade = DowngradeMutToRef::Normal;
                if o.downgrade_mut_inside_shared && mtbl == Mutable {
                    mtbl = self.expr.scrutinee_mutability()?;
                    if mtbl == Shared {
                        downgrade = DowngradeMutToRef::ForceReadOnly;
                    }
                }
                let preds = pats
                    .iter()
                    .enumerate()
                    .map(|(i, pat)| {
                        let expr = self.expr.deref(a).field(a, i).borrow(a, mtbl);
                        Self { pat, expr }
                    })
                    .collect();
                Ok((Rule::ConstructorRef(downgrade), preds))
            }
            (P::Tuple(_), T::Ref(_, T::Tuple(_))) => Err(TypeError::TypeMismatch),
            (P::Tuple(_), T::Ref(outer_mtbl, &T::Ref(inner_mtbl, _)))
                if o.match_constructor_through_ref =>
            {
                let mut mtbl = min(outer_mtbl, inner_mtbl);
                let mut downgrade = DowngradeMutToRef::Normal;
                if o.downgrade_mut_inside_shared && mtbl == Mutable {
                    mtbl = self.expr.scrutinee_mutability()?;
                    if mtbl == Shared {
                        downgrade = DowngradeMutToRef::ForceReadOnly;
                    }
                }
                let expr = self.expr.deref(a).deref(a).borrow(a, mtbl);
                Ok((
                    Rule::ConstructorMultiRef(downgrade),
                    vec![Self {
                        pat: self.pat,
                        expr,
                    }],
                ))
            }
            (P::Tuple(_), T::Ref(_, T::Ref(..))) => Err(TypeError::TypeMismatch),
            (P::Tuple(_), T::Ref(_, T::OtherNonRef(_))) => Err(TypeError::TypeMismatch),
            (P::Tuple(_), T::Ref(_, T::Abstract(_) | T::AbstractNonRef(..))) => {
                Err(TypeError::OverlyGeneral(D::Type))
            }
            (P::Tuple(_), T::OtherNonRef(_)) => Err(TypeError::TypeMismatch),
            (P::Tuple(_), T::Abstract(_) | T::AbstractNonRef(..)) => {
                Err(TypeError::OverlyGeneral(D::Type))
            }

            // Dereference rules
            (P::Ref(p_mtbl, p_inner), T::Ref(mut t_mtbl, _)) => {
                let mut rule_variant = InheritedRefOnRefBehavior::EatOuter;
                let mut fallback_to_outer = FallbackToOuter(false);
                let mut reborrow_after = None;

                // We only inspect the binding mode if there are options that need it.
                let must_inspect_bm = matches!(
                    o.inherited_ref_on_ref,
                    InheritedRefOnRefBehavior::EatInner | InheritedRefOnRefBehavior::EatBoth
                ) || (!o.eat_inherited_ref_alone
                    && o.match_constructor_through_ref);
                // Construct the dereferenced expression.
                let expr = if must_inspect_bm && let ByRef(bm_mtbl) = self.expr.binding_mode()? {
                    // The reference is inherited; options differ in their treatment of this case.
                    let underlying_place = self.expr.reset_binding_mode()?;
                    match underlying_place.ty {
                        T::Ref(inner_mtbl, _) => {
                            rule_variant = o.inherited_ref_on_ref;
                            match o.inherited_ref_on_ref {
                                InheritedRefOnRefBehavior::EatOuter => {
                                    if o.simplify_deref_mut && bm_mtbl == Mutable {
                                        underlying_place
                                    } else {
                                        self.expr.deref(a)
                                    }
                                }
                                InheritedRefOnRefBehavior::EatInner => {
                                    let can_eat_inner = match (p_mtbl, *inner_mtbl) {
                                        (Shared, Shared) => true,
                                        (Mutable, Mutable) => {
                                            bm_mtbl == Mutable || o.eat_mut_inside_shared
                                        }
                                        (Shared, Mutable) => o.allow_ref_pat_on_ref_mut,
                                        (Mutable, Shared) => false,
                                    };
                                    if can_eat_inner {
                                        reborrow_after = Some(t_mtbl);
                                        t_mtbl = *inner_mtbl;
                                        underlying_place.deref(a)
                                    } else if o.fallback_to_outer {
                                        fallback_to_outer = FallbackToOuter(true);
                                        if o.simplify_deref_mut && bm_mtbl == Mutable {
                                            underlying_place
                                        } else {
                                            self.expr.deref(a)
                                        }
                                    } else {
                                        return Err(TypeError::MutabilityMismatch);
                                    }
                                }
                                InheritedRefOnRefBehavior::EatBoth => {
                                    let can_eat_inner = match (p_mtbl, *inner_mtbl) {
                                        (Shared, Shared) => true,
                                        (Mutable, Mutable) => {
                                            bm_mtbl == Mutable || o.eat_mut_inside_shared
                                        }
                                        (Shared, Mutable) => o.allow_ref_pat_on_ref_mut,
                                        (Mutable, Shared) => false,
                                    };
                                    if can_eat_inner {
                                        t_mtbl = *inner_mtbl;
                                        underlying_place.deref(a)
                                    } else if o.fallback_to_outer {
                                        fallback_to_outer = FallbackToOuter(true);
                                        if o.simplify_deref_mut && bm_mtbl == Mutable {
                                            underlying_place
                                        } else {
                                            self.expr.deref(a)
                                        }
                                    } else {
                                        return Err(TypeError::MutabilityMismatch);
                                    }
                                }
                            }
                        }
                        T::Tuple(_) | T::OtherNonRef(_) | T::AbstractNonRef(..)
                            if o.eat_inherited_ref_alone =>
                        {
                            if o.simplify_deref_mut && bm_mtbl == Mutable {
                                underlying_place
                            } else {
                                self.expr.deref(a)
                            }
                        }
                        T::Tuple(_) | T::OtherNonRef(_) | T::AbstractNonRef(..) => {
                            return Err(TypeError::InheritedRefIsAlone);
                        }
                        T::Abstract(_) => {
                            return Err(TypeError::OverlyGeneral(D::Type));
                        }
                    }
                } else {
                    self.expr.deref(a)
                };

                // Match the pattern reference against the appropriate type reference.
                let (mut rule, mut expr) = match (p_mtbl, t_mtbl) {
                    (Shared, Shared) | (Mutable, Mutable) => (
                        Rule::Deref(rule_variant, DowngradeMutToRef::Normal, fallback_to_outer),
                        expr,
                    ),
                    (Shared, Mutable) if o.allow_ref_pat_on_ref_mut => (
                        Rule::DerefMutWithShared(rule_variant),
                        expr.borrow(a, Shared).deref(a),
                    ),
                    (Shared, Mutable) | (Mutable, Shared) => {
                        return Err(TypeError::MutabilityMismatch)
                    }
                };

                if let Some(mut mtbl) = reborrow_after {
                    if o.downgrade_mut_inside_shared && mtbl == Mutable {
                        mtbl = expr.scrutinee_mutability()?;
                        if mtbl == Shared
                            && let Rule::Deref(_, downgrade, _) = &mut rule
                        {
                            *downgrade = DowngradeMutToRef::ForceReadOnly;
                        }
                    }
                    // If we were matching under the inherited reference, we restore it here.
                    expr = expr.borrow(a, mtbl);
                }

                let pred = Self { pat: p_inner, expr };
                Ok((rule, vec![pred]))
            }
            (P::Ref(..), T::Tuple(..) | T::OtherNonRef(_) | T::AbstractNonRef(..)) => {
                Err(TypeError::TypeMismatch)
            }
            (P::Ref(..), T::Abstract(..)) => Err(TypeError::OverlyGeneral(D::Type)),

            // Binding rules
            (P::Binding(mtbl, ByRef(by_ref_mtbl), name), _)
                if matches!(
                    o.ref_binding_on_inherited,
                    RefBindingOnInheritedBehavior::AllocTemporary
                ) =>
            {
                // Easy case: we borrow the expression as expected. We rely on rust's lifetime
                // extension of temporaries in expressions like `&&x`.
                Ok((
                    Rule::BindingBorrow,
                    vec![Self {
                        pat: P::Binding(mtbl, ByMove, name).alloc(a),
                        expr: self.expr.borrow(a, by_ref_mtbl),
                    }],
                ))
            }
            (P::Binding(mtbl, ByRef(by_ref_mtbl), name), _) => {
                match self.expr.binding_mode()? {
                    // Easy case: we borrow the expression as expected.
                    ByMove => Ok((
                        Rule::BindingBorrow,
                        vec![Self {
                            pat: P::Binding(mtbl, ByMove, name).alloc(a),
                            expr: self.expr.borrow(a, by_ref_mtbl),
                        }],
                    )),
                    ByRef(_) => {
                        match o.ref_binding_on_inherited {
                            // To replicate stable rust behavior, we inspect the binding mode and skip it.
                            // This amounts to getting ahold of the referenced place and re-borrowing it
                            // with the requested mutability.
                            RefBindingOnInheritedBehavior::ResetBindingMode => Ok((
                                Rule::RefBindingResetBindingMode,
                                vec![Self {
                                    pat: self.pat,
                                    expr: self.expr.reset_binding_mode()?,
                                }],
                            )),
                            RefBindingOnInheritedBehavior::Error => Err(TypeError::RefOnRef),
                            RefBindingOnInheritedBehavior::AllocTemporary => unreachable!(),
                        }
                    }
                }
            }
            (P::Binding(Mutable, ByMove, _), _)
                if matches!(
                    o.mut_binding_on_inherited,
                    MutBindingOnInheritedBehavior::Keep
                ) =>
            {
                // Easy case: declare the binding as expected.
                Ok((Rule::Binding, vec![]))
            }
            (P::Binding(Mutable, ByMove, _), _) => {
                match self.expr.binding_mode()? {
                    // Easy case: declare the binding as expected.
                    ByMove => Ok((Rule::Binding, vec![])),
                    ByRef(_) => {
                        match o.mut_binding_on_inherited {
                            // To replicate stable rust behavior, we reset the binding mode.
                            MutBindingOnInheritedBehavior::ResetBindingMode => Ok((
                                Rule::MutBindingResetBindingMode,
                                vec![Self {
                                    pat: self.pat,
                                    expr: self.expr.reset_binding_mode()?,
                                }],
                            )),
                            MutBindingOnInheritedBehavior::Error => Err(TypeError::MutOnRef),
                            MutBindingOnInheritedBehavior::Keep => unreachable!(),
                        }
                    }
                }
            }
            (P::Binding(Shared, ByMove, _), _) => Ok((Rule::Binding, vec![])),

            (P::Abstract(..), _) => Err(TypeError::OverlyGeneral(D::Pattern)),
        }
    }
}
